### ISSUE TITLE
Connection check fails on insufficient privileges

### ISSUE THREAD

**Issue by GabyUnalaq** [eclipse-ankaios/ank-sdk-rust#16]
If a workload using the SDK is started with very restricted privileges, e.g., read only "workloadStates", the creation of the `Ankaios` instance returns an Error, which is not right because the result is a valid and it shows that the connection is established. This makes the Rust SDK unusable.

This bug is present in the Python SDK as well: https://github.com/eclipse-ankaios/ank-sdk-python/issues/69

## Current Behavior
`Ankaios::new()` returns an `Err` if the verification fails with insufficient privileges.

## Expected Behavior
`Ankaios::new()` should not fail.

## Steps to Reproduce

1. Modify the `examples/manifest.yaml` by specifying allow rules:
```yaml
...
    controlInterfaceAccess:
      allowRules:
        - type: StateRule
          operation: ReadWrite
          filterMask:
            - "desiredState.workloads"
            - "workloadStates"
...
```
2. Run the `hello_ankaios` example:
```sh
cd examples
./run_example.sh hello_ankaios
```
3. Access the logs using podman. The result should be similar to this:
```sh
thread 'main' panicked at src/main.rs:22:40:
Failed to initialize: AnkaiosResponseError("Access denied")
stack backtrace:
...
```

## Final result

**To be filled by the one closing the issue.**
